### ISSUE TITLE
Missing Content-Type Header in Http Response

### ISSUE THREAD

**Issue by EdSF** [KalikoCMS/KalikoCMS.Core#102]
Just checking if anyone has noticed, **or** experiencing,  missing `Content-Type:text/html` in the `Http Response`. 

I'm only querying since this could just be me. I stumbled on this while doing some "audits"  - e.g. headers security - e.g. `X-Content-Type-Options:nosniff`, which pretty much was how I found out...

I don't think this is a biggie as browsers typically can handle this on their own _except_ when setting the custom header above on browsers that comply with it - e.g. Chrome is one, and after I set that header, it just showed raw HTML (source). Removing the custom header "hides" this or makes this matter moot.

Alternatively I'm currently simply handing this at the app level (`global.asax`) and setting the headers (globally).

Thanks and happy holidays everyone :)

**Comment by fschultz** [comment]
I don't know how I could have missed responding to this, I'm very sorry for it :(

I suspect this can be connected with how the controllers are executed compared to normal MVC execution. I'll look into it. 

Once again apologizes for the huge delay in reply!

**Comment by fschultz** [comment]
Finally got around to fix this. The solution was to flush the response before completing the request, otherwise the content type header wasn't passed through although the content was.

Pre-release packages (version 1.2.5-beta1) that address this issue are available at https://www.nuget.org/packages?q=kalikocms

**Comment by fschultz** [comment]
Final release of version 1.2.5 which targets this issue is available now at https://www.nuget.org/packages?q=kalikocms
