### ISSUE TITLE
Site Settings - Sort Children By Not Reordering Children

### ISSUE THREAD

**Issue by oh-yeah** [KalikoCMS/KalikoCMS.Core#118]
When changing the "Sort children by" values on the CmsSite class and saving/publishing the changes, child pages are not reordered.  This is reproducible on the demo site.

Steps To Reproduce:
- Login to the Cms and Navigate to the "Admin" section
- Select the parent node on the tree view (ex. Demosite)
- Change the "Sort children by" values to PageName and Descending
- Click Publish changes
- Bug -> Child pages are not reordered

**Comment by fschultz** [comment]
Thanks for the bug reports and the exemplary descriptions of how to reproduce. Much appreciated!

**Comment by fschultz** [comment]
Pre-release packages (version 1.2.5-beta1) that address this issue are available at https://www.nuget.org/packages?q=kalikocms

**Comment by fschultz** [comment]
Final release of version 1.2.5 which targets this issue is available now at https://www.nuget.org/packages?q=kalikocms
