### ISSUE TITLE
Cms Page Allows Stop Publish Date before the Start Publish Date

### ISSUE THREAD

**Issue by oh-yeah** [KalikoCMS/KalikoCMS.Core#120]
The Stop publish date should not be able to be before the Start publish date.  This can be reproduced in the Demo Site.

Steps to Reproduce
- Login to the Cms and Navigate to the Admin Section
- Alter any published page
- Enter a Stop publish date that is before the Start publish date
- Bug -> Page allows Stop publish values before the Start publish value

**Comment by fschultz** [comment]
A fix for this issue has been released in the new 1.2.1 version.

For more information about the new version:
http://kaliko.com/blog/new-in-kaliko-cms-1.2.1/
