### ISSUE TITLE
Property Editors do not work

### ISSUE THREAD

**Issue by AbhayShiro** [KalikoCMS/KalikoCMS.Core#126]
I am facing an issue, for some reason the Editor Box for editing collection property do not open when the page loads. It throws the following error:
```
Uncaught TypeError: Cannot read property 'registerCallback' of null
    at Object.openDialog (VM118 CollectionPropertyEditor.js?v=27665445:22)
    at HTMLButtonElement.onclick (VM157 EditPage.aspx?id=a44e8312-a626-4a9c-9cbe-ba1f5cfc60af:276)
openDialog @ VM118 CollectionPropertyEditor.js?v=27665445:22
onclick @ VM157 EditPage.aspx?id=a44e8312-a626-4a9c-9cbe-ba1f5cfc60af:276
```

It will work fine on reload. I think there is a problem with JavaScript parsing i.e. page loads before javascript is parsed. Am I right??

Please help me solve this issue!!!!

**Comment by fschultz** [comment]
Thanks for the bug report! I suspect that this is related to #125. I've identified the problem that is caused by lost references. I'll be posting a temporary work-around soon.

To ensure that this work-around also solves your problem, which browser and version are you using?

**Comment by fschultz** [comment]
I've published a workaround at https://nuget.kaliko.com/ version number 1.2.3-beta1
Hopefully this temporarily solves your problem while I try to come up with a better solution.

**Comment by AbhayShiro** [comment]
Hi @fschultz 
Thanks for your response. 
I regret to inform you that this issue is not fixed yet.
![image](https://user-images.githubusercontent.com/17011750/28557552-be247b86-712a-11e7-8db1-0ed95560c35a.png)

The following is my package.json
![image](https://user-images.githubusercontent.com/17011750/28557588-e9e7104e-712a-11e7-9df6-6bb4d0a44192.png)

See i searched for 1.2.3 version, I couldn't find it on NuGet. Please see below:
![image](https://user-images.githubusercontent.com/17011750/28557618-1cf73fae-712b-11e7-9c38-f2911ffb4259.png)

I am using the following browser:
![image](https://user-images.githubusercontent.com/17011750/28557656-580f5248-712b-11e7-8e5b-56f7c165bb37.png)


Is there any way to make the JS file render everytime? Because I noticed that it works fine on reload.

**Comment by AbhayShiro** [comment]
Hi @fschultz 

 I tried the trick you mentioned [here](https://github.com/KalikoCMS/KalikoCMS.Core/commit/bc8249e97bb8341af1373683c180c99a4f68097a) 

This is the script section I updated in base.master
![image](https://user-images.githubusercontent.com/17011750/28557917-eea2c32e-712c-11e7-9c73-7a67e4db0b31.png)

Please note that (2) `<asp:ContentPlaceHolder ID="AdditionalScripts" runat="server" />` is required.
Also at (1) I have added the code found here on this file : [CollectionPropEditorNoExec.js](https://github.com/KalikoCMS/KalikoCMS.Core/blob/bc8249e97bb8341af1373683c180c99a4f68097a/KalikoCMS.Admin/Admin/Content/PropertyType/CollectionPropertyEditorNoExec.js)

By the above trick, yeah it works. Thanks mate.

**Comment by fschultz** [comment]
Thanks for the feedback. The 1.2.3-beta1 packages should be available by adding https://nuget.kaliko.com/nuget as a NuGet repository and selecting pre-releases to be listed in the package manager.

Good to hear that you got it working by manually making the changes, but sorry to hear about the new issues. Regarding the new problems you're experiencing, do you get any error message in the web browser console?

**Comment by fschultz** [comment]
I've uploaded a fix for the property editor issue in Chrome that replaces the previous temporary fix, available as a pre-release at:
https://www.nuget.org/packages/KalikoCMS.Core/1.2.3-beta2

**Comment by fschultz** [comment]
Final version 1.2.3 released
