### ISSUE TITLE
Response.Write on page on save in CMS /admin

### ISSUE THREAD

**Issue by AbhayShiro** [KalikoCMS/KalikoCMS.Core#128]
I have noticed this issue when I am editing a CMS page.
After editing a page when I press save button, the data gets saved, but the following line gets printed on the screen too:
![image](https://user-images.githubusercontent.com/17011750/28654618-5b2d6bde-72b3-11e7-8b26-c76014c46f3d.png)

Can anyone tell why this is happening.

**Comment by fschultz** [comment]
It seems that you are getting a JavaScript command rendered outside a <script>-scope. On page save the command is added to a Literal that is placed inside a script-block.

This is a wild guess, but could you update your Base.Master to https://raw.githubusercontent.com/KalikoCMS/KalikoCMS.Core/1.2.3-dev/KalikoCMS.Admin/Admin/Templates/MasterPages/Base.Master ?
I noticed in your screenshot regarding the other issue that the original content placeholder "AdditionalScripts" had been renamed to "ContentPlaceholder1" (something Visual Studio can do sometimes).

**Comment by AbhayShiro** [comment]
> Literal that is placed inside a script-block
That was the issue.

@fschultz Yes bro, you are right. Thanks for the fix.

**Comment by fschultz** [comment]
Great to hear that it solved the issue! :)
