### ISSUE TITLE
Error on CMS - Admin/Content - duplicate panel

### ISSUE THREAD

**Issue by severina1** [KalikoCMS/KalikoCMS.Core#129]
Sometimes when I open the /Admin/Content page, I get 2 instances of the content. Then it is difficult to work on it further. Is there any specific reason as to why this happens? Attatched is the screen shot of the issue
![image](https://user-images.githubusercontent.com/30863052/29121121-ddba1968-7d2a-11e7-9602-f3c4c595ee6d.png)

**Comment by kalikocom** [comment]
Do you get this error immediately when opening a page or through clicking on a property editor (for instance an image)? If the latter it's an issue currently being worked on. If the former it's a new issue and it would be great to know what browser version you are running to be able to recreate the problem. Thanks!

**Comment by severina1** [comment]
No, this error does not come when the page is immediately opened. I get it when I click on any page (for example : Education services) in the left hand pane in order to edit the properties for that page. Thanks.

**Comment by fschultz** [comment]
I've tried to reproduce but haven't managed to get the same error. Could you provide the following information to help me to troubleshoot this problem, thanks!

What web browser version are you using?

What version of Kaliko CMS are you running?

Is this problem limited to one web browser or does it appear in other web browsers as well?

**Comment by fschultz** [comment]
I've uploaded a fix for another issue #125 available as a pre-release at:
https://www.nuget.org/packages/KalikoCMS.Core/1.2.3-beta2

This is not the same as the issue you are facing, but it might be worth a try to upgrade since this fixes a JavaScript problem in Chrome.

**Comment by severina1** [comment]
I will update it and test it after a release, Thanks.

**Comment by fschultz** [comment]
New version finally released, hopefully it will solve the issue you've encountered.
