### ISSUE TITLE
When you create a new page running in virtual folder, published Url returns duplicate ApplicationPath

### ISSUE THREAD

**Issue by larjse** [KalikoCMS/KalikoCMS.Core#138]
Virtual folder: /MySite
Create new page: Test
Resulting Published Url: /MySite/MySite/test

The base page returned from the PageFactory (var basePage = PageFactory.GetPage(_pageId);) has duplicated ApplicationPath
WorkAround: If I move the page to another level in the tree and back then the ApplicationPath will be correct.

**Comment by fschultz** [comment]
Thanks for the information! I will look into it.

**Comment by fschultz** [comment]
I've published a new pre-release version; https://www.nuget.org/packages/KalikoCMS.Core/1.2.4-beta2 that should solve the problem with duplicate application paths.

Stort tack för hjälpen med att identifiera buggen så att den blev åtgärdat!

**Comment by fschultz** [comment]
Stable version of 1.2.4 released
