### ISSUE TITLE
Wrong parsing

### ISSUE THREAD

**Issue by net4u** [KalikoCMS/KalikoCMS.Core#142]
Hi

I have an issue with HTML content that is rendered as test as results in the print-screen:

https://www.dropbox.com/s/q6yltgc84x809zt/print-screen.png?dl=0

What may be the cause?

regards

**Comment by fschultz** [comment]
Hi,
When using a HTML property in a view, using only the property name will select the proper HtmlString rendering (outputing HTML):
```
  <div> @Model.CurrentPage.MainBody </div>
```

While for instance @Model.CurrentPage.MainBody.Value would render as text. (It could however also be solved by using @Html.Raw(Model.CurrentPage.MainBody.Value) ).

Hope that helps!

**Comment by net4u** [comment]
Yes, it works. thnx

**Comment by net4u** [comment]
But I notticed something, I don't know that is bug or not:
When I paste some raw html code into editor (source mode), supposing that it contains something like
<img src="./images/myimage.png />
after saving the page, the content is changed into
<img src="./Admin/content/images/myimage.png />

**Comment by fschultz** [comment]
Sorry for the delayed answer, missed the post.

This is a bug, the editor should not try to rewrite the image path and I'll add this as an issue to fix. 
Thanks!

**Comment by fschultz** [comment]
Pre-release packages (version 1.2.5-beta1) that address this issue are available at https://www.nuget.org/packages?q=kalikocms

**Comment by fschultz** [comment]
Final release of version 1.2.5 which targets this issue is available now at https://www.nuget.org/packages?q=kalikocms
