### ISSUE TITLE
Cannot read property 'registerCallback'

### ISSUE THREAD

**Issue by severina1** [KalikoCMS/KalikoCMS.Core#143]
I have an image, on click of it the image, a popup appears and the image can be updated. But, when I click on the image the following error appears in the browser console and the popup is not displayed.  However, on refreshing the screen, the pop up appears.

> VM232 ImagePropertyEditor.js?v=27665445:29 Uncaught TypeError: Cannot read property 'registerCallback' of null
>     at Object.openDialog (VM232 ImagePropertyEditor.js?v=27665445:29)
>     at HTMLAnchorElement.onclick (EditPage.aspx?id=9c6afd8e-d255-47aa-bdc0-becf24a99804:220)

**Comment by fschultz** [comment]
This sounds like issue #125 that should have been fixed by the 1.2.3 release. What version are you running?

**Comment by severina1** [comment]
Thanks. We are using version 1.2.2.  We will upgrade and check.
