### ISSUE TITLE
Move page dialog will not close

### ISSUE THREAD

**Issue by fencer** [KalikoCMS/KalikoCMS.Core#146]
When moving a page, the confirm dialog will pop up however if you click on OK the dialogue will not close (even after the actual page is moved). You will need to press cancel.

**Comment by fschultz** [comment]
This resembles a bug that should have been fixed in release 1.2.1. A couple of question to try to track this bug down:
Which version are you using? Does this occur in a specific web browser or in several?

**Comment by fencer** [comment]
V 1.2.3.0 in Chrome 68.0.3440.106 for sure. however I just realised that this only happens when moving out a page from it's parent page to the root.

**Comment by fschultz** [comment]
I can verify this problem and it also exist in the latest beta build. I will look into it, thanks for reporting!

**Comment by fschultz** [comment]
New beta release including this fix is coming in a few days.

**Comment by fschultz** [comment]
I've published a new beta version that should fix this issue. You'll find it here:
https://www.nuget.org/packages/KalikoCMS.Core/1.2.4-beta5

**Comment by fschultz** [comment]
Stable version of 1.2.4 released
