### ISSUE TITLE
FileProperty not working in collection of CompositeProperty

### ISSUE THREAD

**Issue by olibowork** [KalikoCMS/KalikoCMS.Core#147]
Hi,
i have a little problem with the FileProperty.

First i defined a class (TestProperty) derived from CompositeProperty, containing said property of type FileProperty:

[Property("Video")] 
public FileProperty VideoFile { get; set; }

Second i defined a PageType-Class, derived from CmsPage. To this class i added:         

[Property("List of tests", TabGroup = "Testlist")]
public virtual CollectionProperty<TestProperty> Tests{ get; set; }

Now, when administrating the site, i can add a new entry to the list "Tests", but when i try to set the path to an uploaded file it fails. I can select the file, but the path is not entered into the Video-Field. Database has also a null-value.

Using version 1.2.3 in latest Firefox and Edge browser

**Comment by fschultz** [comment]
Thanks for reporting, I will try to recreate the problem and look into a solution.

**Comment by fschultz** [comment]
I've published a new beta version that should fix this issue. You'll find it here:
https://www.nuget.org/packages/KalikoCMS.Core/1.2.4-beta5

**Comment by fschultz** [comment]
Stable version of 1.2.4 released
