### ISSUE TITLE
LinkProperty stop openening editor in the admin area.

### ISSUE THREAD

**Issue by olibowork** [KalikoCMS/KalikoCMS.Core#151]
Hi,
i created a pagetype with a CollectionProperty of a type, which itself is of type of CompositeProperty. In my scenario i added 3 items to the collection. These items have a LinkProperty.
When editing these items in the admin-area, the first attempt is usualy succesfull. Trying to open the editor of an other item in the collection may fail sometimes. The webdebugger will show in this cases:

TypeError: top is null ImagePropertyEditor.js:29:13
openDialog
http://localhost:6663/Admin/Content/PropertyType/ImagePropertyEditor.js:29:13
onclick
http://localhost:6663/Admin/Content/:1:1

TypeError: top is null LinkPropertyEditor.js:13:13
openDialog
http://localhost:6663/Admin/Content/PropertyType/LinkPropertyEditor.js:13:13
onclick
http://localhost:6663/Admin/Content/:1:1

The problem disapear when saving / publishing the page and than reopening the corresponding editor, but users may not expect this to do. Is there any way to prevent this behavior.

thanks in advance
Oliver

**Comment by fschultz** [comment]
Thanks for reporting! This is a reference error that can appear depending on the order of modals opened. I had hoped it had been solved completely but this seems to be a remaining occurrence, I'll look into it.

**Comment by fschultz** [comment]
Pre-release packages (version 1.2.5-beta1) that address this issue are available at https://www.nuget.org/packages?q=kalikocms

**Comment by fschultz** [comment]
Final release of version 1.2.5 which targets this issue is available now at https://www.nuget.org/packages?q=kalikocms
