### ISSUE TITLE
Feature request: Increase admin site request size limit

### ISSUE THREAD

**Issue by Matthew-Bonner** [KalikoCMS/KalikoCMS.Core#157]
Getting the following error due to the amount of content added to a page, this can easily be fixed by adding a setting to the web.config file for the path /Admin/ which allows requests to be bigger than the default setting in IIS:

![image](https://user-images.githubusercontent.com/7858744/55886659-149b5880-5ba4-11e9-9073-b56fa441784c.png)

I suspect if others make extensive use of the CMS they will come across the same issue.

I would advise against making this a site wide change, so that it just impacts on the /Admin/ path only.

**Comment by Matthew-Bonner** [comment]
Something like the following in the root web.config file would work...

	<location path="Admin">
	  <system.web>
	    
	    <httpRuntime maxRequestLength="51200" />
	  </system.web>
	  <system.webServer>
	    <security>
	      <requestFiltering>
	        
	        <requestLimits maxAllowedContentLength="52428800" /> 
	      </requestFiltering>
	    </security>
	  </system.webServer>
	</location>

**Comment by fschultz** [comment]
Good idea, I'm adding these settings to the web.config template in the next version so that new installations can benefit from allowing larger request sizes while in edit mode.
Thank you very much!

**Comment by fschultz** [comment]
Pre-release packages (version 1.2.5-beta1) that address this issue are available at https://www.nuget.org/packages?q=kalikocms

**Comment by fschultz** [comment]
Final release of version 1.2.5 which targets this issue is available now at https://www.nuget.org/packages?q=kalikocms
