### ISSUE TITLE
registerElement deprecated in chrome

### ISSUE THREAD

**Issue by fencer** [KalikoCMS/KalikoCMS.Core#158]
the version of jsTree used in Kaliko is making use of registerElement, this will be deprecated in June this year and thus will break Kaliko. I am still using version 1.2.3.0 but from what I can see the latest version still has this issue.
![image](https://user-images.githubusercontent.com/620966/57580195-d779fd00-74a6-11e9-9250-d435cac730c0.png)

**Comment by fschultz** [comment]
Thank you very much for the information! Will prioritize this for the next release.

**Comment by fschultz** [comment]
Pre-release packages (version 1.2.5-beta1) that address this issue are available at https://www.nuget.org/packages?q=kalikocms

**Comment by fschultz** [comment]
Final release of version 1.2.5 which targets this issue is available now at https://www.nuget.org/packages?q=kalikocms
