### ISSUE TITLE
Add default sort method for childpages

### ISSUE THREAD

**Issue by fschultz** [KalikoCMS/KalikoCMS.Core#17]
Parent page will decide default sort order for children by either:
- Page name
- Publish date
- Manual sort order
- Modified date

**Comment by yemoku** [comment]
Not sure if this is related to sort order, but items in a cms:MenuList change order if edit. For example Setup a "Home" page. Then setup a "Contact" Page. The contact Page will always show first before the "Home" page in the cms:MenuList.

**Comment by fschultz** [comment]
Yes, it somewhat is. Each page has a sort order value and cms:MenuList default sort mode is to use this sort value. Unfortunately there's no way to set this value through the UI in the current version. It has been added to the 1.0.0-beta-branch, but until it's released the only way to manually set the sort order is through the SortOrder column of the Page table in the database (or by editing the page through code).

This issue will add the possibility to set in which order child pages will be displayed in for instance the admin UI.

**Comment by EdSF** [comment]
Possible bug  actually - looking at the db `Page` table, the `SortOrder` value is 0 for all items, unless something's off in my setup. 

I'm on MVC so I don't have/use the `MenuList` control referenced above but can see the issue manifest in Admin. Moving page (order) isn't actually persisted (hierarchy is fine - re: moving "child" to/from other "parent").

So far, I can get around it (e.g. via `PageName` using `PageFactory.GetChildrenForPage`) and "enforcing" some _hard-coded_ sort/display order in front end....

**Comment by fschultz** [comment]
Currently using drag and drop in the tree for sorting is not implemented. It's a feature that I plan to implement but need to get the parent controlled sort-order in place first.

Version 1.0.0-beta introduced advanced options to manually set the sort value from within the editor:
![sortorder](https://cloud.githubusercontent.com/assets/8556597/8620672/5c6c6cfa-2721-11e5-8b6c-dfc9d19c8304.png)

I hope to get the improved sorting feature in place soon.

**Comment by EdSF** [comment]
That looks awesome! 

And yes, I can also see - the "sitemaps" option - uncanny, I was going to start tinkering with that..trying to figure out how (or if) I could integrate the [ASP.NET MVC SiteMapProvider](https://github.com/maartenba/MvcSiteMapProvider).

Looking good!

**Comment by fschultz** [comment]
Cool! Will be interesting to hear how it works out with the MVC SiteMapProvider integration

**Comment by fschultz** [comment]
New sort features documented at http://kaliko.com/blog/new-in-kaliko-cms-1-0-0/#sorting
