### ISSUE TITLE
Manually set page URL

### ISSUE THREAD

**Issue by fschultz** [KalikoCMS/KalikoCMS.Core#23]
Add option in admin UI to manually set the URL of a page.

**Comment by yemoku** [comment]
Yes this is necessary as the Engine automatically assigns a name that cannot be edited. Even tried directly editing the record in the PageInstance table in the database but it still shows the old URL name

**Comment by fschultz** [comment]
The code have been written and will be in the 1.0.0-beta-release. It also include a fallback system to handle redirects when the URL segment is changed.

Editing the PageInstance table should do the trick, but since the URL segments are cached in memory the application pool need to be reset after any change in the database.

**Comment by yemoku** [comment]
Leading on from this, is there a recommended approach for specifying links to non content managed pages? For example, if I wanted to add a menuitem that points to ~/MyAccount/Myportal.aspx only for authenticated users?

So my main menu would look like thus: 
Home - Portal - Contact - About
with Home  - Contact - About 
controlled via the CMS and Portal with the above specified link

Thanks

**Comment by fschultz** [comment]
I would add an additional page type which only purpose would be to redirect to a specified URL (through a property). (The forum-link under http://kalikocms.com/ is handled that way)

If you only want to show the item for specific users (as per-page authorization hasn't been added yet) you could either filter the pages manually and feeding them to the DataSource property of the MenuList or you could create a page type that handles the redirect especially for authenticated users and use the PageTypeList property of the MenuList to either include pages of that type or not whether the user.
