### ISSUE TITLE
Javascript issues

### ISSUE THREAD

**Issue by yemoku** [KalikoCMS/KalikoCMS.Core#26]
Greetings,

Great design. But there are Javascript issues with other browsers when using the administration pages to create a new page from one of the page types. It works fine in IE (11), but has problems in Chrome Version 40.0.2214.115 & Firefox (using Waterfox)

**Comment by fschultz** [comment]
Thank you for the feedback! I will look into the problem.

**Comment by fschultz** [comment]
Could you please provide me with more information on the JavaScript issues that occur? I've tested the UI in Chrome 40.0.2214.115 without running into any problem (running the DemoSite.WebForms project through Visual Studio's IIS Express).

**Comment by yemoku** [comment]
Apologies,

Please find attached two files in respect of the issue. Kaliko Prob.jpg is a screenshot of the Create Page dialog showing the two page types that I had defined in my project. You can see that the Close button is disabled, and I was not able to select either page.

KalikoCMSCSharp.jpg is actually a zip file of the Visual Studio project (minus the assemblies). Just rename the .jpg extension to  zjp in order to use. (Github only allows images to be uploaded for some reason)

Let me know if you need any more info.

Thanks

![kaliko prob](https://cloud.githubusercontent.com/assets/11268797/6481689/ed23646e-c25f-11e4-9a4c-fff2f4521a83.jpg)

![kalikocmscsharp](https://cloud.githubusercontent.com/assets/11268797/6481705/12c706b2-c260-11e4-9702-d6318d52ec04.jpg)

**Comment by fschultz** [comment]
Thanks for the additional information. It seems that the modal isn't initiated with the correct height and that the page type links is blocked by the modal footer. Although I can't reproduce this in my browser versions I now know where to search in the code. Hope to get back with a solution to the problem soon.

**Comment by yemoku** [comment]
>  Although I can't reproduce this in my browser versions I now know where to search in the code
Just to confirm: I upgraded my version of Chrome to the latest Version 41.0.2272.76 m and there's no issue. I upgraded  Waterfox (64-bit firefox) to 36.0 and there's still an issue. As long as Chrome and IE are working for me

**Comment by yemoku** [comment]
I suspect you can reproduce this error by having a smaller browser window open (instead of full screen). Since you dynamically create the dialog, if there is not enough screen real estate it triggers an error when the dialog is cerated and the user will not be able to select a page type.

Let me know if you have any further questions if the above is not clear.

**Comment by fschultz** [comment]
Should be solved in version 1.0.0-beta
