### ISSUE TITLE
Relative Path for FileLogger

### ISSUE THREAD

**Issue by yemoku** [KalikoCMS/KalikoCMS.Core#27]
Hello,
You may wish to consider implementing relative paths on your FileLogger (log4net?) component. The entry in your web,config in the sample Webforms demo is set to C:\temp\cms-log.txt, and, after deploying it to a remote IIS server, I was unable to implement a relative path such as ~/temp or /temp. 
  <loggers>
  	<fileLogger filename="C:\temp\cms-log.txt" treshold="Major" />
  </loggers>

Also, isnt "treshold" a typo? Shouldn't it be "Threshold"?
Thanks

**Comment by fschultz** [comment]
Good point, the old version relies on a current directory which is not ideal for using it in a web application. I will make a new version of the logger that will be able to use the application folder as a starting point for a relative path.

And you're correct, it should be "Threshold".

Thanks for the feedback! Both fixes will be in the next version.

**Comment by fschultz** [comment]
I've updated the logger to allow relative paths and also added the option to start the path with |DataDirectory| in order to reference the App_data-folder directly. The new package is available through NuGet: https://www.nuget.org/packages/Kaliko.Logger/1.1.1
