### ISSUE TITLE
User Management - Delete User/Role

### ISSUE THREAD

**Issue by yemoku** [KalikoCMS/KalikoCMS.Core#28]
1)
Having a few issues with managing users. Attempts to delete a user resolves to:
http://localhost/Admin/Identity/Identity/DeleteUser.aspx?id=XXX
instead of 
http://localhost/Admin/Identity/DeleteUser.aspx?id=XXX
The same exists for DeleteRole
http://localhost/Admin/Identity/Identity/DeleteRole.aspx?id=XXX
instead of 
http://localhost/Admin/IdentityDeleteRole.aspx?id=XXX

2) 
Do you have plans for allowing the developer to implement their own identity management pages instead, or are they tied to the implemented functionality?

**Comment by fschultz** [comment]
Thank you for the bug reports, much appreciated!

1) Seems to be an issue with the paths, I will look into it.

2) The authentication is decoupled from the CMS itself. So it's quite possible to use any other authentication framework than KalikoCMS.Identity or forking/extending the KalikoCMS.Identity project (https://github.com/KalikoCMS/KalikoCMS.Core/tree/master/KalikoCMS.Identity) with own features and pages. The magic code that registers the admin area to the dashboard can be found in KalikoCMS.Identity/Register/IdentityStartup.cs, this can be used to add a custom dashboard item.

**Comment by yemoku** [comment]
"Thank you for the bug reports, much appreciated!"
Not a problem at all. Reworked your Webforms sample into VB.NET & deployed to a remote host, so discovered a few teething issues that I had to resolve. You may wish to note, for example, that Microsoft.Owin broke when it was version 3.0 so had to ensure that all the Owin components were 2.1.0 in order to get the deployment to work. You might want to test against that. 

Your framework/model is an "easy to understand" design which is great. Let us all know when you plan to release the final version

**Comment by fschultz** [comment]
Should be working in 1.0.0
