### ISSUE TITLE
Debug Messages

### ISSUE THREAD

**Issue by yemoku** [KalikoCMS/KalikoCMS.Core#31]
Hello,

Is there any way to turn off the debug messages that are out put to the Debug window when run in Visual Studio?

Also, any further update on Release 1.0.0-beta?

Thanks

**Comment by fschultz** [comment]
Hi,
Sorry for the delay in response. What kind of messages do you get in the debug window?

Unfortunately the development of 1.0.0-beta has been a bit slow, but I hope to get the page version functionality in place pretty soon.

**Comment by yemoku** [comment]
OK. I am getting messages from the Telerik OpenAccess component:
eg
Telerik.OpenAccess Information: 351 : driver.pool.alloc           18 active=1/10 idle=4/10 con=-842352756
Telerik.OpenAccess Information: 352 : driver.stat.execQuery       2 SELECT a.[RedirectId] COL1, a.[LanguageId] COL2, a.[PageId] COL3, a.[Url] COL4, a.[UrlHash] COL5 FROM [Redirect] a ORDER BY a.[RedirectId]  []
Telerik.OpenAccess Information: 353 : driver.rs.close
Telerik.OpenAccess Information: 354 : driver.pool.release         18 active=0/10 idle=5/10 con=-842352756

**Comment by fschultz** [comment]
I really wonder where they come from. The only information I find regarding tracing/logging in Data Access is when using the visual designer (which isn't used); http://docs.telerik.com/data-access/developers-guide/tracing-and-logging/data-access-tasks-tracing-and-logging-enable-log
Do you have any additional data context in your project?

**Comment by yemoku** [comment]
> Do you have any additional data context in your project?
No, actually I don't. I was wondering whether you might have the following setting "Write Log Output to Console" set to true when you compile as described in Approach 2 in this article:
http://www.telerik.com/help/openaccess-classic/openaccess-tasks-howto-trace-sql-statements.html

**Comment by fschultz** [comment]
This is a pretty strange case. The fluent/code only model doesn't seem to have any settings for tracing/loging, except when specified by code (through BackendConfiguration.Logging) which the project doesn't do. But the Telerik Data Access Enhancer does a bit of magic at compile time. I've looked through the config file for the enhancer, but cannot find any references to trace/logging. Might have to check with Telerik if there's some default setting that needs to be overridden or if I totally have missed something.

**Comment by fschultz** [comment]
After digging a bit more it seems that the BackendConfiguration class has a default setting to write events to trace, but only errors.

If I manually add the following line:
BackendConfiguration.Logging.LogEvents = LoggingLevel.All;
..I get the same type of trace information that you see. But I can't really understand why we get different traces by default without it specifically set.

**Comment by yemoku** [comment]
Ok. No worries. You can treat this as a low priority issue for now

**Comment by fschultz** [comment]
I'll try to fix this in the 1.0.0-beta version once I've finished the page versioning.

**Comment by fschultz** [comment]
I've now added code to specifically set the debug level. Although it should have defaulted to errors-only it seems it didn't in all environments.

I will be rolling out 1.0.0-beta during the week to come - which I hope will be solving this problem as well as a couple of the others you've run into.

**Comment by fschultz** [comment]
I've published an unofficial first beta version of 1.0.0 to http://nuget.kaliko.com/ 
(To get the 1.0.0-beta1 version remember to switch NuGet to "Include Prereleases")

I hope that setting the debug level to errors only will solve the problem you had with output to the debug window (as I can't recreate the issue).

The new 1.0.0-beta1 version also includes:
* Added Markdown property type
* Added option to set URL segment when editing a page
* Added option to set sort order when editing a page
* Added option to set visibility in sitemaps when editing a page
* Added page versioning
* Added page published event
* Added function to fetch all pages based on a predicate filter
* Fixed support for application paths in page URLs
* Fixed support for abstract (inehrited) MVC controllers
* Fixed property HTML output for Razor views
* Fixed default log path to use the |DataDirectory| alias
* Fixed bug overwriting image preview in editor

**Comment by yemoku** [comment]
Updated my project to beta2 and the debug messages have been removed.

Thanks

**Comment by fschultz** [comment]
Great! Thanks for the feedback
