### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by agsteel** [KalikoCMS/KalikoCMS.Core#33]
Hello ,
I was testing the CMS with visual studio 2010 framework 4.0 , but when I try to install Kaliko CMS ASP NET Identity providers get an error "Could Not Install package " Microsoft.Owin 3.0.0 " , how can I fix it?
thanks

**Comment by fschultz** [comment]
I will try to look into it. Have you tried to install the Owin-packages directly before the identity provider?http://www.nuget.org/packages/Microsoft.Owin.Host.SystemWeb/

**Comment by fschultz** [comment]
Just realized that Owin 3.0.0+ only contains binaries targeting ASP.NET 4.5. I will look into if it will be possible to targeting an older version that also is 4.0 compatible.

**Comment by yemoku** [comment]
As far as I recall, the default install of 0.9.9 fails with Owin 3.0.0. In my case, I downgraded owin to 2.1.0.0 in order to get it to work

**Comment by agsteel** [comment]
I tried to install Owin version 2.1 but after when I try to install Kaliko CMS ASP NET Identity providers  via NuGet this delete the Owin old version and try to install the 3.0 giving me back the error and then rollback the procedure

**Comment by yemoku** [comment]
Ok. I see the problem. Even if you install OWIN 2.1.0, the Microsoft.Owin.Security package targets the .NET 4.5 framework as a minimum: http://stackoverflow.com/questions/23239813/how-to-install-owin

**Comment by fschultz** [comment]
Thanks for the input! Much appreciated. I'm aiming to push out the first beta of 1.0.0 during the week to come. I will also try to get AspNet.Identity.DataAccess up-to-date and test it against both OWIN 2.1.0 and 3.0.0+ in an attempt to solve the problems you've had. Before the beta goes official on nuget.org it will be available on a private NuGet repository in order to ensure release quality. I will post the URL so that you can access the packages during this time.

**Comment by fschultz** [comment]
Major setback. When going through references it seems that Microsoft ASP.NET Identity is .NET 4.5 only (seems to be due to code using async etc).

**Comment by agsteel** [comment]
ok thanks , I await new feedback when you solve the problem.

**Comment by yemoku** [comment]
@agsteel If you're tied into using VS2010 (and if you have time) you may wish to consider this hack: http://stackoverflow.com/questions/12390175/targeting-net-framework-4-5-via-visual-studio-2010

**Comment by fschultz** [comment]
I would recommend using .NET 4.5 to make use of ASP.NET Identity. If not possible, a work around could be to use the older membership provider approach.

Unfortunately this will require a bit of manual work:
https://msdn.microsoft.com/en-us/library/879kf95c.aspx

If using SQLite there's a 3rd party implementation here:
http://www.codeproject.com/Articles/29199/SQLite-Membership-Role-and-Profile-Providers

On a side note, Microsoft has a free community edition of Visual Studio (in functionality same as Professional):
https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx
