### ISSUE TITLE
Values that contain markup are encoded during render

### ISSUE THREAD

**Issue by EdSF** [KalikoCMS/KalikoCMS.Core#34]
Pretty new to this and really liking it so far! 

As the title says, I'm having to do `@Html.Raw` for Properties that have HTML markup. So straight out of the "Getting Started", in order to get things going:

- `@Html.Raw(Model.TopImage.ToHtml())`
- `@Html.Raw(Model.MainBody.Value)`

Currently only have the Nuget install (not source), so I guess this is an "fyi" for now....

BTW, really like the approach - _"doesn't set boundaries"_ == awesome!

**Comment by fschultz** [comment]
Thank you very much for the feedback!

I'm currently trying to get the first beta release of 1.0.0 ready for release later this week. Will aim to fix this so that the HTML return values can be used directly.

**Comment by fschultz** [comment]
I've published an unofficial first beta version of 1.0.0. It's available here: http://nuget.kaliko.com/ (remember to switch NuGet to "Include Prereleases" to access 1.0.0-beta1) and will after some testing be promoted to nuget.org.

The following should now render proper non-encoded HTML:
```
@Model.TopImage.ToHtml()
@Model.MainBody
```
(Notice that Value on the HtmlPropery still will return a string that will be encoded, but just addressing the property with @Model.MainBody will result in a proper HtmlString).
