### ISSUE TITLE
KalikoCMS Providers

### ISSUE THREAD

**Issue by yemoku** [KalikoCMS/KalikoCMS.Core#36]
Greetings,

Do you have any tips/instructions on developing custom providers for KalikoCMS? I noticed that you provided the source for a RaptorDB provider, but no instructions on how to plug it into the framework and the required datamodel. 

Is this an approach that you have considered enabling others to do? Instead of RaptorDB, I wanted to ascertain how much effort it would be to create a custom provider for something like Microsoft Access, and have it auto-create the datamodel as it currently does with SQLLite

Thanks

**Comment by fschultz** [comment]
I apologize for the current lack of documentation regarding some areas of the CMS.

The RaptorDB provider is a sample on how to implement an object store other than the built in. More about the object stores can be found here; http://kaliko.com/cms/get-started/data-store/

The CMS uses Telerik DataAccess as data provider. And all database systems supported by DataAccess is available to use with the CMS.

Although the documentation and preconfigured NuGet-packages lacks for other databases, the following should work well; http://kaliko.com/cms/knowledge-base/supported-databases/
Unfortunately Microsoft Access is not one of them.

**Comment by yemoku** [comment]
Ok thanks
