### ISSUE TITLE
Testing Release 1.0.0-beta - SQLLite Nuget version conflict

### ISSUE THREAD

**Issue by yemoku** [KalikoCMS/KalikoCMS.Core#37]
Ok. Have done a completely fresh install with both SQLServer & SQLLite providers. 
There's a dependency somewhere on System.Data.SQLite, Version=1.0.86.0, whilst the Nuget package installs System.Data.SQLite.Core" version="1.0.97.0"

**Comment by yemoku** [comment]
Ok. KalikoCMS.Data.SQLite depends on System.Data.SQLite, Version=1.0.86.0. Interestingly enough, I couldn't find version Version=1.0.86.0 on nugget, so will install from an older project

**Comment by fschultz** [comment]
Thanks for the feedback! Did you get any error due to the difference in dependency and installed package?It seems they unlist all older SQLite packages at nuget.org.
I really hope that the NuGet framework switch to "get latest version" kind of dependencies in the future. Currently I'm referencing which lower version that is compatible but that also means that NuGet resolves the dependency to the lowest compatible version and not the latest which would be much better.

**Comment by yemoku** [comment]
>> Did you get any error due to the difference in dependency and installed package?
There were no nugget install errors. All the 1.0 pre-release packages installed seamlessly. However compiling the project fails with the missing version 1.0.86 despite of course 1.0.97 loaded.

Once I uninstalled 1.0.97 & replaced with 1.0.86 everything worked.

>> It seems they unlist all older SQLite packages at nuget.org.
If that is the case then there's a risk that the KalikoCMS version 0.99 release may be broken when doin a fresh install

**Comment by fschultz** [comment]
It just hit me that I've run into this problem before and a work-around is written down in the readme.txt that comes with the SQLite provider;
https://github.com/KalikoCMS/KalikoCMS.Core/blob/master/KalikoCMS.Data.SQLite/readme.txt

I don't really know why this is working fine in some environments but not in others. I have two different machines and one resolves without problem to verion 1.0.97 whereas the other displays the same error that you get.

I would really like to find out why and make a more permanent solution.

**Comment by yemoku** [comment]
Please crosscheck whether you are using the same .Net Framework versions for your OpenAccess DLLs. Noticed that Telerik.OpenAccess & Telerik.OpenAccess.Runtime are v2.0.50727. Should they be v4.0.30319? A quick check on the machine where its working should confirm.

Built another Visual Studio with Nugets to the packages, but same problem: SQLite version 1.0.97 is installed but 1.0.86.0 is required for the KalikoCMS.Data.SQLite provider

**Comment by fschultz** [comment]
The both DLLs seems to be compiled for .NET 2.0 independent of target framework but for .NET 4.0+ an additional Telerik.OpenAccess.40.Extensions.dll is added to the project. So the versions referenced seems to be fine.

The 1.0.86.0 problem is inherited from the Data Access. The current way to solve it is to add an assembly building (as in the readme.txt above) but I hope to have a code approach to fix this transparently. Will test out the code later today on the machine that has the problem.

**Comment by fschultz** [comment]
I've added a fix for this in 1.0.0-beta2 that's currently available at http://nuget.kaliko.com/I will be rolling out the beta2 to nuget.org later today.

**Comment by yemoku** [comment]
A fresh new Visual Studio solution build and install correctly implemented version 1.0.97. You can close out this issue. Good job!

**Comment by fschultz** [comment]
Thanks for the feedback!
