### ISSUE TITLE
SetupAdminAccount.aspx & OWIN customizations

### ISSUE THREAD

**Issue by yemoku** [KalikoCMS/KalikoCMS.Core#38]
Noticed this behaviour in both releases. If you make any changes to the default OWIN behaviour whilst setting up a new project, these changes are not reflected at runtime.

Example:
In the ApplicationUserManager Create method, make a change to manager.PasswordValidator by setting  RequiredLength = 5, OWIN will still prompt the user to create a password of minimum of 6 characters

**Comment by fschultz** [comment]
I will look into it. Thanks for reporting!

**Comment by fschultz** [comment]
Sorry for the late response. The problem is that the Owin context isn't used but instead a default UserManager is created when users are created, both in the initial setup page but also within the admin UI. I will fix this in the next version (1.1.0)

**Comment by fschultz** [comment]
Besides reference the updated KalikoCMS.Identity existing projects need to update the following files:
**IdentityConfig.cs** https://github.com/KalikoCMS/KalikoCMS.Core/commit/dc4eb10cc9355744f64ea1035dad551c6b1e8e5f#diff-8350f2838377b82e7e14e4d10c31117a

**Startup.Auth.cs** https://github.com/KalikoCMS/KalikoCMS.Core/commit/dc4eb10cc9355744f64ea1035dad551c6b1e8e5f#diff-ef7c0a70ac9892ac1d2bfb873a7d70a8

**SetupAdminAccount.aspx** https://github.com/KalikoCMS/KalikoCMS.Core/commit/dc4eb10cc9355744f64ea1035dad551c6b1e8e5f#diff-46a6112a12e06cbe2d9ce23d51e5a2ab

**Comment by yemoku** [comment]
Great stuff! Will download and give feedback.

**Comment by yemoku** [comment]
Cool. It works. Seeing as you hadnt released any code I had to "hack around a bit". Here's what I did:
1) Created a new project and used Nuget to get all the relevant references
2) Made code changes as per your instructions
3) Downloaded your Kaliko.Identity Source and referenced in my solution, removing the compiled Nuget version and removed the duplicate startup.cs in the downloaded source
4) Changed the password validator code to do a minimum of 4 chars for a new password
5) Logged in as Admin and created a new user with 4 chars for a new password

You can close out this entry once you ship your updated  1.1.0 version (or mark as fixed for that version if you wish)

**Comment by fschultz** [comment]
Thanks for the feedback! I hope to have 1.1.0 ready pretty soon if all goes well.
