### ISSUE TITLE
Html Editor Language Character

### ISSUE THREAD

**Issue by barisakpunar** [KalikoCMS/KalikoCMS.Core#40]
Html editor does not properly save Turkish Language Characters 'ş','ğ'  etc.
I think it is related with json serialization.

**Comment by fschultz** [comment]
Thanks for the feedback! I did a quick test and managed to save both 'ş' and 'ğ' in my test setup. I agree it do sound like a serialization (or database) issue.

What version do you have of fastJSON.dll? (My test setup is running 2.1.14.0)

What database provider do you use? (I tested on SQLite)

Does this problem also occur in text fields?

**Comment by barisakpunar** [comment]
I am using the same version fastJson.
At first I looked at the tinymce source view after I wrote Turkish Characters. 
And I found the problem it doesn't show correctly. 
And I added   entity_encoding : "raw" settings to tinymce and it became correct in the source view.

I solved the problem in TinyMCE.

But When I looked at database ( SQL Server 2012) PageProperty Table the Html Property is not properly saved. Database PropertyData column type is nvarcharMAX so it can be written special characters.

So I guess fastjson serialization is the problem. If it has some settings about encoding I guess problem will be solved.

yes the problem is also in text fields.

**Comment by fschultz** [comment]
I'll continue to look into the problem.

**Comment by fschultz** [comment]
Does the characters look like this encoded in the PageProperty table?:
![temp](https://cloud.githubusercontent.com/assets/8556597/8619677/38c14526-2719-11e5-97c5-1093e6f16b8d.png)

For me they appear correct in the editor, but on the site I need to specify that the characterset is UTF-8 in order to make them appear correctly (<meta charset="UTF-8" />).

**Comment by barisakpunar** [comment]
Thank you.
When the page is UTF-8  it is OK.

**Comment by fschultz** [comment]
Great! Thanks for the feedback
