### ISSUE TITLE
Encoding (or serialization)

### ISSUE THREAD

**Issue by EdSF** [KalikoCMS/KalikoCMS.Core#42]
On an editor, if the `text` or `string` provided contains a single quote, a JavaScript syntax error is hit (`top.executeCallback`) - re: "missing `)` ".

e.g. `hello's world`

results in 
` <script> top.executeCallback('{"Value":"hello's world"}', 'hello&#39;s world'); top.closeModal(); </script>`

[Line 51 of EditCollectionPropertyDialog.aspx.cs](https://github.com/KalikoCMS/KalikoCMS.Core/blob/master/KalikoCMS.Admin/Admin/Content/Dialogs/EditCollectionPropertyDialog.aspx.cs#l51) is probably the place to look at...though it seems `excerpt` var "should" be the right var to use (?).

**Comment by fschultz** [comment]
Thanks for the detailed error report! Made it very easy to fix :)

The first parameter contains the complete serialized property that is sent back to the collection and the second the encoded preview that is shown in the list. I've added encoding of apostrophe characters which would prevent the callback script to break.

**Comment by EdSF** [comment]
:+1:

**Comment by fschultz** [comment]
Should be working in 1.0.0-beta3 now available at NuGet (also in the master branch)
