### ISSUE TITLE
FindSimular never returns results

### ISSUE THREAD

**Issue by dotnetshadow** [KalikoCMS/KalikoCMS.Core#61]
Hi,

I was wondering how the FindSimular works, I used the following, but the FindSumlar always returns 0 results. I tried the search function and it was able to find things. So I know the indexing is working but when I try FindSimular it doesn't. I'm using  Kaliko CMS 1.0.1 but I noticed the Search version is 1.0.0

I even tried just having the title property and category but I still can't get ti to work correctly? It could be due to what content is on the page. Does there have to be a minimum length of words? If I had a title called "This is a test" and another page had "This is a test too" do you think those should be related?

        public IndexItem MakeIndexItem(CmsPage page)
        {
            // Get a strongly typed version
            var typedPage = page.ConvertToTypedPage<ArticlePage>();

            // Create a base index item
            var indexItem = typedPage.GetBaseIndexItem();

            indexItem.Title = typedPage.Heading.Value;
            indexItem.Summary = typedPage.Excerpt.Value;
            indexItem.Content = typedPage.Content.Value;
            indexItem.Tags = typedPage.Tags.ToString();
            indexItem.Category = "Article";

            return indexItem;
        }

FindSimular:
 var searchResult =  SearchManager.Instance.FindSimular(Model,  0, 5);

<h4>Related</h4>
        <ul class="list-unstyled related">

            <p>@searchResult.Hits.Count</p>

            @foreach (var searchHit in searchResult.Hits)
            {
            
            <li><a href="@searchHit.Path">@searchHit.Title</a></li>
            }
        </ul>

**Comment by fschultz** [comment]
Hi! I will look into it. Just two quick questions; how many pages do you have in your search index with the same category ("Article") and do you get any result if you add the 4th parameter (used to set if only to return hits matched on category, default set to true) to false: `SearchManager.Instance.FindSimular(Model, 0, 5, false)`?

**Comment by dotnetshadow** [comment]
I think I pin pointed the problem to indexItem.Category whenever I have that on no results show.

I have 11 pages indexed and yes when I set the parameter to false I started to see some results.

**Comment by fschultz** [comment]
Great, then we've really narrowed it down :) Have you tried to reindex all the pages (from the search tab in the admin UI)?

**Comment by dotnetshadow** [comment]
Yes I have with various combinations but it seems when I set all the pages to use .Category = "Article" then I get no results if I set the parameter to true

**Comment by fschultz** [comment]
Ok, then it's likely a code issue. I hope to get some time to troubleshoot this later tonight. By the way, forgot to answer this before, but the versioning of the search implementation and the CMS differ sometimes. Only when there are changes in the search API or any changes in the search code itself a new version is released. At the moment Kaliko CMS 1.0.1 should use Kaliko Search 1.0.0.

**Comment by fschultz** [comment]
Found the problem while looking at the search index. It's connected with how the index stores the category when it comes to some category names. "Article" for instance is stored as "articl" (which I guess is because of the analyzer).

If you change to `indexItem.Category = "Item";` the `FindSimular` function will work like it should.

I'm prioritizing this issue and will push a separate **KalikoCMS.Search** release when done.

**Comment by dotnetshadow** [comment]
Excellent, good work, just a quick question about the indexing in general when you use something like this:
 indexItem.Content = typedPage.Content.Value;

Is there somewhere documented what all the properties are? Can they be extended to include custom properties or how does it all work? Or does it predominately analyze the content and makes an assessment on that when using FindSimular?

**Comment by fschultz** [comment]
`FindSimular` uses **title**, **summary**, **content** and **tags** to match documents.

It's possible to add additional properties by using the MetaData:
`indexItem.MetaData.Add("myproperty", typedPage.SomeProperty);`

These are however not used in searches. Search uses **title**, **summary**, **content**, **tags** and **category**. These default properties is only to structure the indexed content except for **category** that also is used to separate hits when using the default setting of `FindSimular`.

To include a custom property in the search result, add its name to the `MetaData` property:
```
  var searchQuery = new SearchQuery(query) {
    MetaData = new[] {"category", "summary", "myproperty" }
  };

  // Perform the searh
  var result = SearchManager.Instance.Search(searchQuery);
```
Looping through the result set you can then access the property through `searchHit.MetaData["myproperty"]`

Search is a feature that is long due for some upgrades and documentation. Will most likely work on things like being able to specify which fields to search in (also for FindSimular) and also seeing more about the index within the administration UI when I'm done with the 1.1.0 version.

**Comment by dotnetshadow** [comment]
Exactly what I was looking for, look forward to the updates ahead, yes having the ability to search on various fields would be cool. Is there any special syntax for the searchQuery "AND" / "OR" etc?

**Comment by fschultz** [comment]
Yes, you can use "AND"/"OR"/"NOT" and "+" (and)/"-" (not) and even specify searches in fields "title:wordintitle". You can also group these boolean queries such as "(always OR demo) AND find". "+"/"-" works pretty much as Google's search used to; "+find always -demo" will require "find", exclude "demo" and optional "always". I'll update the documentation with a few examples later today.

**Comment by fschultz** [comment]
I've added some query examples over at http://kaliko.com/cms/get-started/search-engines/#querysyntax

**Comment by dotnetshadow** [comment]
Good examples of the syntax look forward to using them
