### ISSUE TITLE
ByRef value type parameter cannot be null.

### ISSUE THREAD

**Issue by dotnetshadow** [KalikoCMS/KalikoCMS.Core#63]
Hi, 
I seem to get this error whenever I try to use html helper such as @html.Label("test") with any page that has a CMSPage type. If I just use a normal Controller and View the html helper works

**Type**
```
[PageType("ArticleLandingPage", "Article Page - Landing", PageTypeDescription = "Create an Article Landing Page", AllowedTypes = new[] { typeof(ArticleLandingPage), typeof(ArticlePage) }, PreviewImage = "Assets/Images/article-landing-page-type.png")]
    public class ArticleLandingPage : CmsPage
    {
        [Property("Heading")]
        public virtual StringProperty Heading { get; set; }

        [Property("Content")]
        public virtual HtmlProperty Content { get; set; }

        [Property("Excerpt")]
        public virtual TextProperty Excerpt { get; set; }

        [Property("Description")]
        public virtual StringProperty Description { get; set; }

        [Property("Keywords")]
        public virtual StringProperty Keywords { get; set; }

        [TagProperty("Categories", TagContext = "articlelandingcategories")]
        public virtual TagProperty Categories { get; set; }

        [TagProperty("Tags", TagContext = "articlelandingtags")]
        public virtual TagProperty Tags { get; set; }

    }
}
```

**Controller**
```
   public class ArticlesLandingPageController : PageController<ArticleLandingPage>
    {
        public override ActionResult Index(ArticleLandingPage currentPage)
        {            
            return View(currentPage);
        }
    }
```

**View**
```

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
<div>
    This is a test
    @Html.Label("test")
</div>
</body>
</html>
```

![capture](https://cloud.githubusercontent.com/assets/296247/10066838/22cceb60-62da-11e5-9bd2-9ace89988501.PNG)

**Comment by fschultz** [comment]
Strange, haven't seen this one before. Will take a look later today.

**Comment by fschultz** [comment]
This is a really weird error. I've duplicated it using your code. It seems to have something to do with the model. If I create a view model and attach the current page to it the page works like it should, but if the model is the page the above error is displayed.

**Comment by fschultz** [comment]
`@Html.LabelFor(x => x.Content)` works as expected, but not `@Html.Label("test")`. I'm starting to think that there might be some issue with the model binding, because I can't really think of anything else that might cause this.

**Comment by fschultz** [comment]
Finally located the error, it was down in the PageProxy class. Will fix this and create a temporary release tomorrow to use before the planned 1.1.0 gets out.

**Comment by dotnetshadow** [comment]
Great work, yeah I never seen an error like that before myself. Just for my own knowledge what does the PageProxy class do anyway?

**Comment by fschultz** [comment]
I've fixed this in a separate branch and will roll out NuGet-packages later:
https://github.com/KalikoCMS/KalikoCMS.Core/tree/proxy-hotfix

The PageProxy class is responsible for taking a CmsPage and exposing it as a strongly typed page. This mostly consist of taking all the virtual properties defined on the page type and map them toward the property collection (dictionary containing all custom page data).

I'm very grateful for your help in getting this errors found so they can be fixed! :)

**Comment by fschultz** [comment]
I've placed a package with a hotfix (KalikoCMS.Core.1.0.1-hotfix1) at http://nuget.kaliko.com/
(Be sure to check "include prereleases" in order to see the correct version within Visual Studio)

This fix will also be included in the upcoming 1.1.0 version that is close around the corner.

**Comment by dotnetshadow** [comment]
Thanks for that I tried through nuget package manager but it doesn't get listed for some reason even with pre release ticked.

**Comment by fschultz** [comment]
Thanks for the feedback, it seems that I should have upped the version number to ensure the package to be recognized as an update to 1.0.1.
