### ISSUE TITLE
Importing pages

### ISSUE THREAD

**Issue by dotnetshadow** [KalikoCMS/KalikoCMS.Core#64]
Hi there,

Is there any API or ways to import pages into the system without using the UI? I was looking at your PageFactory class but I don't see a way of creating any pages. It would be handy to have a way of doing this so we can import articles / pages from existing systems.

**Comment by fschultz** [comment]
Yes. It's done through a CmsPage instance that will act as the parent to the created page. Use the method CreateChildPage on the parent page object with the type of page you want to create. You'll get an editable page copy back in return from that method that you can use to set the properties you want. Custom properties (as specified in the page type) is set by calling SetProperty(propertyName, propertyData) - where property data is an instance of the property type you specified in the page type. 

Once all properties are set you need to first call Save() on the child page and then Publish(). If you don't want the page to be published directly you call Publish(true) which doesn't affect the page state but put it in the site tree. 

I'll put up an example of this tonight.

**Comment by dotnetshadow** [comment]
That is awesome. Thank you so much I'll have a go at this

**Comment by fschultz** [comment]
Didn't get around to get the documentation page up, so here's a small sample instead:

// Get the root to use as parent to the new page
var parentPage = PageFactory.GetPage(SiteSettings.RootPage);

// Create a new page of type TestPage
var childPage = parentPage.CreateChildPage(typeof (TestPage));childPage.PageName = "My new page";childPage.SetProperty("Header", new StringProperty("This is a code generated page!"));childPage.Save();childPage.Publish();

**Comment by dotnetshadow** [comment]
Hi there,

I tried your sample and was able to import pages, but I found the even if I run the search index that the search findsimular doesn't work unless I save the page again in the GUI?

**Comment by dotnetshadow** [comment]
I'm not sure if my query for displaying the findsimular could be the issue:

var searchResult =  SearchManager.Instance.FindSimular(Model,  0, 5, false);

//var relatedReults = searchResult.Hits.Where(x => (PageFactory.GetPage<ArticlePage>(x.PageId).Series == null) || ((PageFactory.GetPage<ArticlePage>(x.PageId).Series != null) && PageFactory.GetPage<ArticlePage>(x.PageId).Series.Value != seriesName)).ToList();

I'm not sure how I could use in my query x.MetatData["series"], I seem to get 'The given key was not present in the dictionary' error message

**Comment by fschultz** [comment]
Strange, Publish() should trigger the same functionality as in the GUI. I will check it out. On a side note, Luke (https://code.google.com/p/luke/) is a pretty good tool to debug the search indexes.

**Comment by fschultz** [comment]
I need to verify but I suspect the FindSimular function only returns the standard fields. If so, the method should be extended in the same way as search with a specified list of additional fields wanted.

**Comment by dotnetshadow** [comment]
You are correct i seem to get results when using searchResult.Hits with no filtering.

Yes if a list of additional fields could be passed in that would be great

**Comment by dotnetshadow** [comment]
Thanks for the hint on Luke I'll definitely give it a try

**Comment by fschultz** [comment]
I've added a new issue for this (#66) to be included in the upcoming 1.1.0 version.

**Comment by dotnetshadow** [comment]
Excellent news, look forward to the 1.1.0 version. Do you how far that would be?

**Comment by fschultz** [comment]
I'm almost done with #54, then there's just #56 and #66 to go. So it shouldn't be too far away.
