### ISSUE TITLE
Error DateTimeProperty, wrong namespace for property editor. 

### ISSUE THREAD

**Issue by willemhoog** [KalikoCMS/KalikoCMS.Core#67]
The file '/Admin/ontent/PropertyType/DateTimePropertyEditor.ascx' does not exist. 

In file DateTimePropery.cs the next line. The 'C' is missing
  [PropertyType("8b631801-10b7-4e99-a05c-e16e9e96bc44", "DateTime", "DateTime", "%AdminPath%ontent/PropertyType/DateTimePropertyEditor.ascx")]

**Comment by fschultz** [comment]
Thanks for reporting! I will fix this and push it out in the upcoming 1.1.0 release.

In the mean time I can recommend using the UniversalDateTimeProperty. It's an improvement over the DateTimeProperty in that it better handles the differences between the client's and server's time zones (for instance when hosting in another time zone): http://kaliko.com/cms/api/kalikocms.engine/kalikocms.propertytype.universaldatetimeproperty/

**Comment by fschultz** [comment]
I've pushed a NuGet pre-release version 1.1.0-beta2 that contain this fix.
