### ISSUE TITLE
ImageProperty adding class

### ISSUE THREAD

**Issue by barisakpunar** [KalikoCMS/KalikoCMS.Core#70]
Is there any way to add class to ImageProperty in the view?

**Comment by fschultz** [comment]
When rendered on page or also able to set in the editor? Currently it requires custom code, but adding an overloaded way to render the HTML tag for the image with more control over additional attributes - such as class - is a good idea to add. 


     On Wednesday, October 21, 2015 3:34 PM, Barış Akpunar <notifications@github.com> wrote:
   

 Is there any way to add class to ImageProperty in the view?—

**Comment by barisakpunar** [comment]
In fact I can use FileProperty but I want to also give the user cropping functionality. But since ImageProperty render with full image tag ( as should be) I can't insert a class or style to image tag.

I think these details should be made on the page.  Not set on the editor. Editor will be bloated with details then.

Maybe ImageProperty should only render src attribute of image tag like FileProperty. Only difference between them image crop and sizing functionality.

**Comment by fschultz** [comment]
Thanks for the input! I'll extend the ImageProperty with a method that better control the output in the upcoming 1.1.0 release.

**Comment by fschultz** [comment]
Samples of the new overloads:

Set class name for the rendered image:
`@Model.CurrentPage.TopImage.ToHtml("top-image")`

Set class name and additional data attribute for the rendered image:
`@Model.CurrentPage.TopImage.ToHtml(new Dictionary<string, string> { { "class", top-image"}, {"data-test", "123"} })`

**Comment by fschultz** [comment]
I've pushed a NuGet pre-release version 1.1.0-beta2 that contain this change.
