### ISSUE TITLE
PageDataStore in MVC

### ISSUE THREAD

**Issue by barisakpunar** [KalikoCMS/KalikoCMS.Core#71]
How can we use PageDataStore in MVC?
Thank you.

**Comment by fschultz** [comment]
In MVC the page data store needs to be created by calling `GetStore` on the `DataStoreManager` class with the page that you wish to get the data store for (usually `currentPage` that was passed to the page controller action):
```c#
var pageDataStore = DataStoreManager.GetStore(currentPage)
```

The created store can then be used for fetching or storing values:
```c#
// To fetch:
var someValue = pageDataStore .Get<TestClass>("MyTest");

// To store:
pageDataStore.Store("MyTest", someValue);
```
