### ISSUE TITLE
Admin panel MVC integration

### ISSUE THREAD

**Issue by barisakpunar** [KalikoCMS/KalikoCMS.Core#72]
Is there a simple way to use MVC in Admin Panel?
Thank you.

**Comment by fschultz** [comment]
At the moment there's no integrated way to add MVC views to the admin panel if you want to keep the common UI parts (like the left side menu etc.). You can however register an MVC admin panel that completely takes over the whole page.

I'm aiming to migrate the complete admin over to MVC one part at the time. And a first step would to be to create a shared layout that mimics the current master page content. If this is something that can be helpful to you I can prioritize this.

**Comment by barisakpunar** [comment]
Yes.It would be great.

**Comment by fschultz** [comment]
Sorry for the delay, I've uploaded an archive with some sample code to include in a project to add a custom admin area using MVC to: https://dl.dropboxusercontent.com/u/5437987/MvcDashboardSample.zip

Hope this helps getting an MVC-based admin area up and running.

**Comment by fschultz** [comment]
Just wanted to check if you've got it all working or need any further assistance/samples?

**Comment by barisakpunar** [comment]
It is all working. Thank you.
