### ISSUE TITLE
SetupAdminAccount.aspx problem

### ISSUE THREAD

**Issue by grahambsa** [KalikoCMS/KalikoCMS.Core#75]
Hello Frederik

The new version sample applications sqlite databases do not contain the role "WebAdmin" so SetupAdminAccount.aspx breaks

(mvc and webforms v1.1)

Kind Regards
Graham

**Comment by fschultz** [comment]
Hello Graham,The SetupAdminAccount.aspx should create both the WebAdmin role as well as the user when executed. If you run that page, do you get any error message?

**Comment by grahambsa** [comment]
Hello Fredrik

I am so sorry ... it was my bad! I did not read the instructions on the
page ... There is NO problem with  the code. *It works as designed!*

Thank you for the very nice CMS ... you have gone to a lot of trouble. I am
still playing around with it

Kind Regards
Graham

**Comment by fschultz** [comment]
No problem, I'm glad it worked out :)

Thank you for the kind words! I hope you'll find the CMS useful.
