### ISSUE TITLE
NuGet packages

### ISSUE THREAD

**Issue by willemhoog** [KalikoCMS/KalikoCMS.Core#76]
Hello,

when I install the  new nugget packages, there are problems when running the site.
Install the kaliko cms core version 1.1.0 it is oke.
Install the kalikom mvc version 1.1.0, error Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information, log file
[Critical] Could not load file or assembly 'Telerik.OpenAccess.35.Extensions, Version=2015.3.926.1, Culture=neutral, PublicKeyToken=7ce17eeaf1d59342' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) | .
Your example mvc application works fine.

The version of Telerik.OpenAcces.35.Extensions which is reference is 2015.2.624.1.

**Comment by fschultz** [comment]
Thank you very much for the bug report! There seems to be an issue with a reference in the installation package. Until the packages are updated this can be fixed by manually updating the Telerik.DataAccess.Core NuGet package to version 2015.3.926.1 in your project.

**Comment by fschultz** [comment]
I've uploaded a package of version 1.1.1-beta to nuget.org that should have the correct references.

**Comment by fschultz** [comment]
Version 1.1.1 just released should fix this issue.
