### ISSUE TITLE
Required CmsPage propertie?

### ISSUE THREAD

**Issue by willemhoog** [KalikoCMS/KalikoCMS.Core#77]
Hey,

I have searched for it but I can't find it.
Is it possible in a page type to set required value for a property?
For example the headline can't not be empty with published or saved.

 [Property("Headline")]
public virtual StringProperty Headline { get; set; }

**Comment by fschultz** [comment]
At the moment there's no generic way to set properties to required. This is a feature that is clearly lacking. I'm flagging this issue for the next major release and will be adding the ability to set `[Required]` attribute to the properties.
