### ISSUE TITLE
Possibility to set options for root page

### ISSUE THREAD

**Issue by fschultz** [KalikoCMS/KalikoCMS.Core#80]
It should be possible to for instance restrict available page types under the root page in the same manner that is possible for page types.

**Comment by fschultz** [comment]
Besides restricting available page types and child sort order this feature includes site based properties.

**Comment by willemhoog** [comment]
Hello,
Can you tell me how this works?
Possibility to set options for root page  #80 ?

**Comment by fschultz** [comment]
Site settings was introduced in version 1.2.0 which allows site wide properties to be set as well as default behavior of the root page.

Adding site settings to a project is done by implementing **CmsSite** and decorate the class with the **SiteSettings**-attribute. In the attribute you can define how the root page should behave (in the same way as with page types) by setting **AllowedTypes**, **DefaultChildSortOrder** and **DefaultChildSortDirection**. Properties are added the same way as on page types.

Here's a sample implementation of CmsSite that implements a few properties and also set which page types are available under the root page and the sort order :
```c#

namespace Demo.Models {
    using KalikoCMS.Attributes;
    using KalikoCMS.Core;
    using KalikoCMS.Core.Collections;
    using KalikoCMS.PropertyType;
    using Pages;

    [SiteSettings(
        AllowedTypes = new[] {typeof(StartPage), typeof(NewsListPage), typeof(BlogListPage), typeof(SearchPage), typeof(StandardPage), typeof(FormPage)},
        DefaultChildSortOrder = SortOrder.SortIndex)]
    public class DemoSite : CmsSite {
        [Property("Cookie information")]
        public virtual HtmlProperty CookieInformation { get; set; }

        [Property("Search page")]
        public virtual PageLinkProperty SearchPage { get; set; }
    }
}
```

For information on how to access the properties from code see; http://kaliko.com/cms/get-started/create-site-settings/
