### ISSUE TITLE
If in PageName is quotes (") used . Page Tree iş not working

### ISSUE THREAD

**Issue by barisakpunar** [KalikoCMS/KalikoCMS.Core#81]
If quotes (") is used in PageName attribute, PageTreeControl in Admin Page is not working. Because when feeding the tree, PageName attributes is used for converting to Json. And quotes (") is breaking the hierarchy of Json. We should validate this before publishing.

**Comment by fschultz** [comment]
Thanks! I've switched the code that feeds the tree with items to use the same JSON serialization as the rest of the system uses. This should handle all JSON incompability. I've also fixed an issue where the quotes also caused a JavaScript error.

**Comment by fschultz** [comment]
I've uploaded a package of version 1.1.1-beta to nuget.org that should be able to handle quotes in the page tree.

**Comment by fschultz** [comment]
Version 1.1.1 just released should fix this issue.
