### ISSUE TITLE
Reference to using DemoSite; in MVC 1.1.1

### ISSUE THREAD

**Issue by yemoku** [KalikoCMS/KalikoCMS.Core#88]
Greetings,

Have installed the MVC version of Kaliko 1.1.1 and, using Razor, the compiler trips up on a reference to using DemoSite; in the compile output. 

Have scoured through all the cshtml files etc and no reference to this. Could this have been compiled into the release? 

A snippet from the compiled code below
Thanks

<
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using DemoSite;
        
    public class _Page_Views_articlepage_index_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_articlepage_index_cshtml() {
        }
        
        protected ASP._global_asax ApplicationInstance {
            get {
                return ((ASP._global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/articlepage/index.cshtml", 1, 5, false);
>

**Comment by fschultz** [comment]
Hi,
That sounds really strange. There should be no reference in any of the NuGet-packages towards the DemoSite-namespace. I really wonder where the compiler picks up that reference.

**Comment by yemoku** [comment]
Ok. Will close this issue out. Must have been something I did. A fresh project and build has not made the issue reoccur.
