### ISSUE TITLE
Problem with URLs and virtual application paths

### ISSUE THREAD

**Issue by fschultz** [KalikoCMS/KalikoCMS.Core#90]
When running a website under a virtual application path the generated URLs gets corrupted. For a virtual application path of "abc" the generated page path gets "/abcpage" instead of expected "/abc/page".

**Comment by BerndHanisch** [comment]
hi,

i installed version 1.2.0-beta3 and still have problems with url in a sub virtual application.

creating an "page"-link the system generate "/MitarbeiterportalTesting/CMSAdmin/intranet/messe/".

"/MitarbeiterportalTesting" is the directory of application
"../CMSAdmin" is the Admin-Code of KalikoCMS

the code should only generate "intranet/messe/"

**Comment by fschultz** [comment]
I'll look into it. Seems it erroneously adds the admin path to the full URL, so it might be a copy&paste-error when I changed the code.

**Comment by fschultz** [comment]
New pre-release released with a fix for a bug when URLs was created for new pages when running in a application path; https://www.nuget.org/packages/KalikoCMS.Core/1.2.4-beta2

**Comment by fschultz** [comment]
Stable version of 1.2.4 released
