### ISSUE TITLE
modify CMSPage dont work with custom dateFormat

### ISSUE THREAD

**Issue by BerndHanisch** [KalikoCMS/KalikoCMS.Core#92]
if <siteSettings .... dateFormat="MM-dd-yyyy HH:mm:ss" /> is set saving a previous created cmspage cant be modified, because on click publish button ==> "on ore more errors occured"

Removing the option dateFormat fix the bug.

Additional where can i get the details of this error message?

**Comment by fschultz** [comment]
Could you provide a bit more information about the code not working?

By default errors are logged to a file in the App_Data-folder. The log file should contain more information about the error.

**Comment by BerndHanisch** [comment]
web.config:
![kaliko-web config](https://cloud.githubusercontent.com/assets/19992326/16197922/2ae357ae-3704-11e6-87fc-12f14c990c32.png)

modify an existing page by click on "publish page"
![kaliko-page-modify](https://cloud.githubusercontent.com/assets/19992326/16198178/43805a22-3705-11e6-99ca-5741e117f7a8.png)


didnt suceed. there is no entry in the logfile.

BTW: great software

**Comment by fschultz** [comment]
Thanks! I'll look into the problem and get back to you as quick as I can.

**Comment by fschultz** [comment]
Found the problem and updated the code to convert to the proper custom format entered in the config. The fix is available in the 1.2.0-dev-branch and I will roll out a new beta version of the NuGet package containing the change within the next few days.

Thanks for reporting!

**Comment by fschultz** [comment]
I've uploaded a new version with th fix (1.2.0-beta2) of the NuGet packages to https://nuget.kaliko.com/

**Comment by fschultz** [comment]
Hi,
just wanted to check if the updated version solved the problem?

**Comment by BerndHanisch** [comment]
Hi,

working now. Thx

**Comment by fschultz** [comment]
Great! Thanks for the feedback
