### ISSUE TITLE
Property value cannot be loaded correctly

### ISSUE THREAD

**Issue by hieudole** [KalikoCMS/KalikoCMS.Core#93]
The GUID value property (such as PageLinkProperty) cannot be loaded correctly when the property editor opens up because the serializer converts that value into fast GUID which may include some special characters that are not allowed in URL.

Quick fix: Disable UseFastGuid in the JsonSerialization.cs file:
`private static readonly JSONParameters GenericParameters = new JSONParameters {UseExtensions = false, UseFastGuid = false };
private static readonly JSONParameters TypedParameters = new JSONParameters { UseExtensions = true, UseFastGuid = false, UsingGlobalTypes = true };`

Updated: This bug is caused when the PageLinkProperty is a member of CompositePropperty.

**Comment by fschultz** [comment]
Thank you very much for reporting the problem and also providing the solution. Will look into it. Thanks!
