### ISSUE TITLE
Specifying Views Folder for KalikoCMS.MVC

### ISSUE THREAD

**Issue by yemoku** [KalikoCMS/KalikoCMS.Core#99]
Greetings. Hope all is well.

I thought I'd have a different/non-standard setup with MVC and respecify the Views folders on a web site. In MVC a class derived from IViewEngine interface would enable you to specify alternate locations.

is there a way in which we could instruct KalikoCMS to use an alternate ~/Views path? 

Thanks

**Comment by yemoku** [comment]
Actually found the solution using code located here: http://stackoverflow.com/questions/2140208/how-to-set-a-default-route-to-an-area-in-mvc The code was not trivial :)

**Comment by fschultz** [comment]
Thank you for posting the solution! :)

**Comment by yemoku** [comment]
Pleasure
